id: ADB8044BC
title: 'All-Pervading Auspiciousness: An Aspiration for the Spread of the Teachings
  of the Eight Great Chariots of the Practice Lineage'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:52:04.197881
  last_modified_at: 2022-03-01 04:52:04.197889
