id: ADB8044BC
title: 'The Seed of Faith: A Prayer to the Sublime Ones'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:52:04.221044
  last_modified_at: 2022-03-01 04:52:04.221046
