id: ADB8044BC
title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:52:04.212371
  last_modified_at: 2022-03-01 04:52:04.212375
