id: ADB8044BC
title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s Teachings
  in Tibet'
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:52:04.215656
  last_modified_at: 2022-03-01 04:52:04.215660
