id: ADB8044BC
title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:52:04.209671
  last_modified_at: 2022-03-01 04:52:04.209678
