id: ADB8044BC
title: 'The Swift Fulfilment of Wishes: A Prayer of Aspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:52:04.222720
  last_modified_at: 2022-03-01 04:52:04.222723
