id: ADB8044BC
title: Aspiration for the Spread of the Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:52:04.202024
  last_modified_at: 2022-03-01 04:52:04.202029
